version: '2'
services:
    northumbriaproms-app:
        image: northumbriaproms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://northumbriaproms-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=northumbriaproms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    northumbriaproms-mongodb:
        extends:
            file: mongodb.yml
            service: northumbriaproms-mongodb
