version: '2'
services:
    northumbriaproms-app:
        image: northumbriaproms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://northumbriaproms-mariadb:3306/northumbriaproms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=northumbriaproms-elasticsearch:9300
        ports:
            - 8080:8080
    northumbriaproms-mariadb:
        extends:
            file: mariadb.yml
            service: northumbriaproms-mariadb
    northumbriaproms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: northumbriaproms-elasticsearch
    northumbriaproms-rabbitmq:
        extends:
            file: rabbitmq.yml
            service: northumbriaproms-rabbitmq
